"""Migrate to original

Revision ID: 666a78df90c2
Revises: 
Create Date: 2025-07-18 08:13:57.472229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666a78df90c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('child_id', sa.INTEGER(), nullable=True),
    sa.Column('test_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('max_score', sa.INTEGER(), nullable=True),
    sa.Column('test_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child.child_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
